### ISSUE TITLE
转载请求~

### ISSUE THREAD

**Issue by violetjack** [PDKSophia/blog.io#2]
Hi，设计模式一文写的很赞，让我收获不少。
想把设计模式一文转载到我的语雀知识库中，可以吗。
谢谢了~

**Comment by PDKSophia** [comment]
> Hi，设计模式一文写的很赞，让我收获不少。
> 想把设计模式一文转载到我的语雀知识库中，可以吗。
> 谢谢了~

可以的，能厚个脸皮，底部求个原文链接~
