### ISSUE TITLE
为什么学这个当博客？

### ISSUE THREAD

**Issue by Lucifer-ww** [PDKSophia/blog.io#3]
我有个弱弱的问题:question:

为什么您使用Github做为博客？我看您的前端技能比我强得多啊，为什么不自己搭建Github Page？

还有好像用仓库搭建博客不好吧，建议去CSDN试试？个人认为掘金一般般……

>纯粹建议，不听没关系

**Comment by PDKSophia** [comment]
> 我有个弱弱的问题❓
> 
> 为什么您使用Github做为博客？我看您的前端技能比我强得多啊，为什么不自己搭建Github Page？
> 
> 还有好像用仓库搭建博客不好吧，建议去CSDN试试？个人认为掘金一般般……
> 
> > 纯粹建议，不听没关系

不瞒你说，我之前有用 `wordpress`、`hexo` 搭过自己博客，后来服务器到期，就没续费了，自然而然博客就挂了，之后也在jianshu上写博客，但是，一是用的不顺手，二是感觉jianshu更像一个`大杂烩`。不像一个纯技术社区~

个人感觉`CSDN` 大部分文章都是互相摘抄，当然，不可否认CSDN确实可以，但一开始我搜文章，查阅资料的时候，大部分都是千篇一律的文章，互相抄袭，撑死底部挂个原文链接，其次是有时候我查一些资料，还需要积分（主要我想白嫖~）所以第一印象不太好~

后来就来到了掘金，当然掘金还算比较小众，但是实话说，它确实是一个技术社区吧~所以就一直停留在掘金了。

至于为什么博客是在Github，这么说吧，我这个博客仓库是18年暑假，秋招时候就开了，当时也是想搭建一个 `Github Page`，奈何失败了~ 啊哈哈哈，在哪跌倒就在哪躺着（滑稽.jpg） 最主要的一个原因是: github 不会哪天说没了就没了，其次是也有看到很多人是在 GitHub 托管博客的，只是他们更多是在 issuse，而随着我博客内容越来越多，迁移比较麻烦，我就不想动了~

**Comment by Lucifer-ww** [comment]
哦，明白了

**Comment by Lucifer-ww** [comment]
:smile:

**Comment by Lucifer-ww** [comment]
我觉得CSDN的阅读量比较高，对我也是一个鼓励，掘金人不多，功能好像也比较少

不过我的项目不多，主要Github是学习用的

**Comment by PDKSophia** [comment]
> 我觉得CSDN的阅读量比较高，对我也是一个鼓励，掘金人不多，功能好像也比较少
> 
> 不过我的项目不多，主要Github是学习用的

因人而异啦，CSDN确实有些文章质量是不错的，juejin更多是我觉得比较多纯技术文章，比较喜欢水而已~

**Comment by Lucifer-ww** [comment]
关掉吧？
